#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🛠 formating..."
nx format:write
echo "✅ format done."
echo "🛠 linting..."
nx run-many --target=lint --fix
echo "🛠 check typescript types ..."
npx nx run-many --target=type-check
echo "✅ types checked."
git add -u
